Repository Capstone-FA25/BookingCareSystemBackend, pull requests merged in 2025-09, with the labels that each got.

#18 Merge request from config/config-api-versioning_HieuMX into develop
  src/ApiGateway/BookingCare.ApiGateway.Ocelot/ocelot.json
  src/ApiGateway/BookingCare.ApiGateway.Ocelot/ocelot.old.json
Labels: config

#14 Merge request feature/favorites-service_TamDN from into develop
  src/Services/BookingCare.Services.Favorites/BookingCare.Services.Favorites.csproj
  src/Services/BookingCare.Services.Favorites/Controllers/FavoritesController.cs
  src/Services/BookingCare.Services.Favorites/Data/FavoritesDbContext.cs
  src/Services/BookingCare.Services.Favorites/Extensions/ServiceCollectionExtensions.cs
  src/Services/BookingCare.Services.Favorites/Mappings/FavoriteMappingProfile.cs
  src/Services/BookingCare.Services.Favorites/Models/Configuration/MongoDbSettings.cs
  src/Services/BookingCare.Services.Favorites/Models/DTOs/FavoriteDTOs.cs
  src/Services/BookingCare.Services.Favorites/Models/Entities/FavoriteEntity.cs
  src/Services/BookingCare.Services.Favorites/Program.cs
  src/Services/BookingCare.Services.Favorites/Protos/greet.proto
  src/Services/BookingCare.Services.Favorites/README.md
  src/Services/BookingCare.Services.Favorites/Repositories/Implementations/FavoriteRepository.cs
  src/Services/BookingCare.Services.Favorites/Repositories/Interfaces/IFavoriteRepository.cs
  src/Services/BookingCare.Services.Favorites/Services/GreeterService.cs
  src/Services/BookingCare.Services.Favorites/Services/Grpc/FavoritesGrpcService.cs
  src/Services/BookingCare.Services.Favorites/Services/Implementations/FavoriteService.cs
  src/Services/BookingCare.Services.Favorites/Services/Interfaces/IFavoriteService.cs
  src/Services/BookingCare.Services.Favorites/Validators/FavoriteValidators.cs
  src/Services/BookingCare.Services.Favorites/appsettings.json
Labels: feature

#22 Merge request from feature/discount-service_HieuMX into develop
  src/Services/BookingCare.Services.Discount/Controllers/DiscountsController.cs
  src/Services/BookingCare.Services.Discount/Models/DTOs/DiscountRequestDtos.cs
  src/Services/BookingCare.Services.Discount/Services/DiscountService.cs
  src/Services/BookingCare.Services.Discount/Services/IDiscountService.cs
Labels: feature

#23 Merge request from config/config-validation-exception_HieuMX into develop
  src/Shared/BookingCare.Shared.Common/Extensions/ExceptionHandlingExtensions.cs
  src/Shared/BookingCare.Shared.Common/Extensions/ValidationExtensions.cs
  src/Shared/BookingCare.Shared.Common/README.md
Labels: config

#26 Merge request from config/config-cors_HieuMX into develop
  src/ApiGateway/BookingCare.ApiGateway.Ocelot/Program.cs
  src/ApiGateway/BookingCare.ApiGateway.Ocelot/appsettings.Development.json
  src/ApiGateway/BookingCare.ApiGateway.Ocelot/appsettings.json
  src/Services/BookingCare.Services.Discount/Dockerfile
Labels: config

#27 Merge request from feature/auth-service_HuyKV into develop
  src/Services/BookingCare.Services.Auth/BookingCare.Services.Auth.csproj
  src/Services/BookingCare.Services.Auth/Constants/AuthConstants.cs
  src/Services/BookingCare.Services.Auth/Controllers/AuthController.cs
  src/Services/BookingCare.Services.Auth/Data/AuthDbContext.cs
  src/Services/BookingCare.Services.Auth/Exceptions/AuthExceptions.cs
  src/Services/BookingCare.Services.Auth/Mappings/AuthMappingProfile.cs
  src/Services/BookingCare.Services.Auth/Migrations/20250904023240_InitialCreate.Designer.cs
  src/Services/BookingCare.Services.Auth/Migrations/20250904023240_InitialCreate.cs
  src/Services/BookingCare.Services.Auth/Migrations/AuthDbContextModelSnapshot.cs
  src/Services/BookingCare.Services.Auth/Models/DTOs/AuthRequestDtos.cs
  src/Services/BookingCare.Services.Auth/Models/DTOs/AuthResponseDtos.cs
  src/Services/BookingCare.Services.Auth/Models/DTOs/AuthUtilityDtos.cs
  src/Services/BookingCare.Services.Auth/Models/DTOs/LoginDtos.cs
  src/Services/BookingCare.Services.Auth/Models/DTOs/RefreshTokenDtos.cs
  src/Services/BookingCare.Services.Auth/Models/DTOs/RegisterDtos.cs
  src/Services/BookingCare.Services.Auth/Models/Entities/AccountEntity.cs
  src/Services/BookingCare.Services.Auth/Models/Entities/AccountRoleEntity.cs
  src/Services/BookingCare.Services.Auth/Models/Entities/PermissionEntity.cs
  src/Services/BookingCare.Services.Auth/Models/Entities/RefreshTokenEntity.cs
  src/Services/BookingCare.Services.Auth/Models/Entities/RoleEntity.cs
  src/Services/BookingCare.Services.Auth/Models/Entities/RolePermissionEntity.cs
  src/Services/BookingCare.Services.Auth/Program.cs
  src/Services/BookingCare.Services.Auth/Protos/auth.proto
  src/Services/BookingCare.Services.Auth/Protos/greet.proto
  src/Services/BookingCare.Services.Auth/Providers/ExternalAuthProviderBase.cs
  src/Services/BookingCare.Services.Auth/Providers/ExternalAuthProviderService.cs
  src/Services/BookingCare.Services.Auth/Providers/IExternalAuthProvider.cs
  src/Services/BookingCare.Services.Auth/Repositories/AuthRepository.cs
  src/Services/BookingCare.Services.Auth/Repositories/IAuthRepository.cs
  src/Services/BookingCare.Services.Auth/Services/AuthGrpcService.cs
  src/Services/BookingCare.Services.Auth/Services/AuthService.cs
  src/Services/BookingCare.Services.Auth/Services/DataInitializationService.cs
  src/Services/BookingCare.Services.Auth/Services/GreeterService.cs
  src/Services/BookingCare.Services.Auth/Services/IAuthService.cs
  src/Services/BookingCare.Services.Auth/Services/Interfaces/IAuthService.cs
  src/Services/BookingCare.Services.Auth/Utils/CookieService.cs
  src/Services/BookingCare.Services.Auth/Utils/JsonConverters.cs
  src/Services/BookingCare.Services.Auth/Utils/JwtService.cs
  src/Services/BookingCare.Services.Auth/appsettings.Development.json
  src/Services/BookingCare.Services.Auth/appsettings.json
  src/Services/BookingCare.Services.Notification/Protos/otp.proto
  src/Shared/BookingCare.Shared.Common/AppRouting/AppRoutingHelper.cs
  src/Shared/BookingCare.Shared.Common/Authorization/DynamicAuthorizationPolicyProvider.cs
  src/Shared/BookingCare.Shared.Common/Authorization/Handlers.cs
  src/Shared/BookingCare.Shared.Common/Authorization/Requirements.cs
  src/Shared/BookingCare.Shared.Common/BookingCare.Shared.Common.csproj
  src/Shared/BookingCare.Shared.Common/Configuration/FrontendConfiguration.cs
  src/Shared/BookingCare.Shared.Common/Configuration/JwtConfiguration.cs
  src/Shared/BookingCare.Shared.Common/Enums/OtpPurpose.cs
  src/Shared/BookingCare.Shared.Common/Enums/Role.cs
  src/Shared/BookingCare.Shared.Common/Examples/ServiceConfigurationExample.cs
  src/Shared/BookingCare.Shared.Common/Extensions/AuthorizationExtensions.cs
  src/Shared/BookingCare.Shared.Common/Extensions/ExceptionHandlingExtensions.cs
  src/Shared/BookingCare.Shared.Common/Extensions/FrontendConfigurationExtensions.cs
  src/Shared/BookingCare.Shared.Common/Extensions/JwtAuthenticationExtensions.cs
  src/Shared/BookingCare.Shared.Common/Extensions/MiddlewarePipelineExtensions.cs
  src/Shared/BookingCare.Shared.Common/Extensions/ServiceConfigurationExtensions.cs
  src/Shared/BookingCare.Shared.Common/Middleware/AutoTokenMiddleware.cs
Labels: feature

#34 Merge request from feature/notification-service-v1_HuyKV into develop
  src/Services/BookingCare.Services.Auth/BookingCare.Services.Auth.csproj
  src/Services/BookingCare.Services.Auth/Services/AuthService.cs
  src/Services/BookingCare.Services.Notification/BookingCare.Services.Notification.csproj
  src/Services/BookingCare.Services.Notification/Constants/ValidationMessages.cs
  src/Services/BookingCare.Services.Notification/Controllers/DeviceController.cs
  src/Services/BookingCare.Services.Notification/Controllers/NotificationsController.cs
  src/Services/BookingCare.Services.Notification/Controllers/OtpController.cs
  src/Services/BookingCare.Services.Notification/Exceptions/NotificationExceptions.cs
  src/Services/BookingCare.Services.Notification/Handlers/NotificationSendEventHandler.cs
  src/Services/BookingCare.Services.Notification/Models/DTOs/NotificationRequestDtos.cs
  src/Services/BookingCare.Services.Notification/Models/Entities/Device.cs
  src/Services/BookingCare.Services.Notification/Program.cs
  src/Services/BookingCare.Services.Notification/Protos/greet.proto
  src/Services/BookingCare.Services.Notification/Protos/otp.proto
  src/Services/BookingCare.Services.Notification/Repositories/Implementations/DeviceRepository.cs
  src/Services/BookingCare.Services.Notification/Repositories/Interfaces/IDeviceRepository.cs
  src/Services/BookingCare.Services.Notification/Services/GreeterService.cs
  src/Services/BookingCare.Services.Notification/Services/Grpc/OtpGrpcService.cs
  src/Services/BookingCare.Services.Notification/Services/Implementations/OtpService.cs
  src/Services/BookingCare.Services.Notification/Services/Interfaces/IOtpService.cs
  src/Services/BookingCare.Services.Notification/Setting/EmailSettings.cs
  src/Services/BookingCare.Services.Notification/Setting/MongoDbSettings.cs
  src/Services/BookingCare.Services.Notification/Utils/Email/EmailService.cs
  src/Services/BookingCare.Services.Notification/Utils/Email/EmailTemplate.cs
  src/Services/BookingCare.Services.Notification/Utils/OTP/ManageOtp.cs
  src/Services/BookingCare.Services.Notification/Utils/SMS/DeviceStore.cs
  src/Services/BookingCare.Services.Notification/Utils/SMS/FcmOptions.cs
  src/Services/BookingCare.Services.Notification/Utils/SMS/FcmV1Service.cs
  src/Services/BookingCare.Services.Notification/appsettings.json
  src/Shared/BookingCare.Shared.Cache/Constants/CacheKeys.cs
  src/Shared/BookingCare.Shared.Cache/Extensions/ServiceCollectionExtensions.cs
Labels: feature

#36 Merge request from feature/doctor-service-favorite into develop
  src/Services/BookingCare.Services.Doctor/BookingCare.Services.Doctor.csproj
  src/Services/BookingCare.Services.Doctor/Controllers/DoctorsController.cs
  src/Services/BookingCare.Services.Doctor/Controllers/LanguageController.cs
  src/Services/BookingCare.Services.Doctor/Controllers/PositionsController.cs
  src/Services/BookingCare.Services.Doctor/Controllers/ServiceTypeController.cs
  src/Services/BookingCare.Services.Doctor/Data/DoctorDbContext.cs
  src/Services/BookingCare.Services.Doctor/Exceptions/DoctorExceptions.cs
  src/Services/BookingCare.Services.Doctor/Exceptions/PositionExceptions.cs
  src/Services/BookingCare.Services.Doctor/Exceptions/PriceExceptions.cs
  src/Services/BookingCare.Services.Doctor/Mappings/DoctorMappingProfile.cs
  src/Services/BookingCare.Services.Doctor/Mappings/PositionMappingProfile.cs
  src/Services/BookingCare.Services.Doctor/Middlewares/DoctorRateLimitingMiddleware.cs
  src/Services/BookingCare.Services.Doctor/Middlewares/DoctorSecurityMiddleware.cs
  src/Services/BookingCare.Services.Doctor/Migrations/20250920013935_init-database.Designer.cs
  src/Services/BookingCare.Services.Doctor/Migrations/20250920013935_init-database.cs
  src/Services/BookingCare.Services.Doctor/Migrations/DoctorDbContextModelSnapshot.cs
  src/Services/BookingCare.Services.Doctor/Models/DTOs/Requests/DoctorRequestDtos.cs
  src/Services/BookingCare.Services.Doctor/Models/DTOs/Requests/LanguageRequestDtos.cs
  src/Services/BookingCare.Services.Doctor/Models/DTOs/Requests/PositionRequestDtos.cs
  src/Services/BookingCare.Services.Doctor/Models/DTOs/Requests/ServiceTypeRequestDtos.cs
  src/Services/BookingCare.Services.Doctor/Models/DTOs/Responses/DoctorResponseDtos.cs
  src/Services/BookingCare.Services.Doctor/Models/DTOs/Responses/LanguageResponseDtos.cs
  src/Services/BookingCare.Services.Doctor/Models/DTOs/Responses/PositionResponseDtos.cs
  src/Services/BookingCare.Services.Doctor/Models/DTOs/Responses/ServiceTypeResponseDtos.cs
  src/Services/BookingCare.Services.Doctor/Models/Entities/DoctorEntity.cs
  src/Services/BookingCare.Services.Doctor/Models/Entities/DoctorLanguageEntity.cs
  src/Services/BookingCare.Services.Doctor/Models/Entities/DoctorPriceEntity.cs
  src/Services/BookingCare.Services.Doctor/Models/Entities/LanguageEntity.cs
  src/Services/BookingCare.Services.Doctor/Models/Entities/PositionEntity.cs
  src/Services/BookingCare.Services.Doctor/Models/Entities/ServiceTypeEntity.cs
  src/Services/BookingCare.Services.Doctor/Program.cs
  src/Services/BookingCare.Services.Doctor/Protos/doctor.proto
  src/Services/BookingCare.Services.Doctor/Protos/greet.proto
  src/Services/BookingCare.Services.Doctor/README.md
  src/Services/BookingCare.Services.Doctor/Repositories/Implementations/DoctorRepository.cs
  src/Services/BookingCare.Services.Doctor/Repositories/Implementations/LanguageRepository.cs
  src/Services/BookingCare.Services.Doctor/Repositories/Implementations/PositionRepository.cs
  src/Services/BookingCare.Services.Doctor/Repositories/Implementations/ServiceTypeRepository.cs
  src/Services/BookingCare.Services.Doctor/Repositories/Interfaces/IDoctorRepository.cs
  src/Services/BookingCare.Services.Doctor/Repositories/Interfaces/ILanguageRepository.cs
  src/Services/BookingCare.Services.Doctor/Repositories/Interfaces/IPositionRepository.cs
  src/Services/BookingCare.Services.Doctor/Repositories/Interfaces/IServiceTypeRepository.cs
  src/Services/BookingCare.Services.Doctor/Scripts/insert_sample_data.sql
  src/Services/BookingCare.Services.Doctor/Scripts/truncate_db.sql
  src/Services/BookingCare.Services.Doctor/Services/GreeterService.cs
  src/Services/BookingCare.Services.Doctor/Services/Grpc/DoctorGrpcService.cs
  src/Services/BookingCare.Services.Doctor/Services/Implementations/DoctorService.cs
  src/Services/BookingCare.Services.Doctor/Services/Implementations/LanguageService.cs
  src/Services/BookingCare.Services.Doctor/Services/Implementations/PositionService.cs
  src/Services/BookingCare.Services.Doctor/Services/Implementations/ServiceTypeService.cs
  src/Services/BookingCare.Services.Doctor/Services/Interfaces/IDoctorService.cs
  src/Services/BookingCare.Services.Doctor/Services/Interfaces/ILanguageService.cs
  src/Services/BookingCare.Services.Doctor/Services/Interfaces/IPositionService.cs
  src/Services/BookingCare.Services.Doctor/Services/Interfaces/IServiceTypeService.cs
  src/Services/BookingCare.Services.Doctor/appsettings.Development.json
  src/Services/BookingCare.Services.Doctor/appsettings.json
Labels: feature

#38 Merge request from hotfix/fix-warnings-build-solution_HieuMX into develop
  src/ApiGateway/BookingCare.ApiGateway.Ocelot/BookingCare.ApiGateway.Ocelot.csproj
  src/Services/BookingCare.Services.AI/BookingCare.Services.AI.csproj
  src/Services/BookingCare.Services.Auth/BookingCare.Services.Auth.csproj
  src/Services/BookingCare.Services.Doctor/Migrations/20250920013935_init-database.Designer.cs
  src/Services/BookingCare.Services.Doctor/Migrations/20250920013935_init-database.cs
  src/Services/BookingCare.Services.Review/Services/Implementations/ReviewService.cs
  src/Services/BookingCare.Services.User/Repositories/UserRepository.cs
  src/Shared/BookingCare.Shared.Common/BookingCare.Shared.Common.csproj
Labels: bug, hotfix

#43 Merge request from config/config-saga-orchestrator-common_HieuMX into develop
  BookingCareSystem.sln
  src/Shared/BookingCare.Shared.Saga/StateStore/SqlServerSagaStateStore.cs
Labels: feature, config

#47 Merge request from hotfix/replace-clinicserviceid-with-serviceid into develop
  src/Services/BookingCare.Services.Review/Controllers/ReviewsController.cs
  src/Services/BookingCare.Services.Review/Exceptions/DuplicateReviewException.cs
  src/Services/BookingCare.Services.Review/Grpc/Services/ReviewGrpcService.cs
  src/Services/BookingCare.Services.Review/Mappings/ReviewMappingProfile.cs
  src/Services/BookingCare.Services.Review/Models/DTOs/ReviewRequestDTOs.cs
  src/Services/BookingCare.Services.Review/Models/DTOs/ReviewResponseDTOs.cs
  src/Services/BookingCare.Services.Review/Models/Entities/ReviewEntity.cs
  src/Services/BookingCare.Services.Review/Protos/ReviewService.proto
  src/Services/BookingCare.Services.Review/README.md
  src/Services/BookingCare.Services.Review/Repositories/Implementations/ReviewRepository.cs
  src/Services/BookingCare.Services.Review/Repositories/Interfaces/IReviewRepository.cs
  src/Services/BookingCare.Services.Review/Services/Implementations/ReviewService.cs
  src/Services/BookingCare.Services.Review/Services/Interfaces/IReviewService.cs
  src/Services/BookingCare.Services.Review/Validators/ReviewValidators.cs
Labels: hotfix
